spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${random.uuid}
            client-secret: ${random.uuid}
            scope: read:user,public_rep
          oauth2-client:
            provider: spring-security-oauth2
            client-id: oauth2-client
            client-name: spring-security-oauth2
            client-secret: "AutW573n6W3bngqoCrAiH8P3UJwm0be"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/oauth2-client
            scope: user:read
        provider:
          spring-security-oauth2:
            authorization-uri: http://172.21.110.93:9000/oauth2/authorize
            token-uri: http://172.21.110.93:9000/oauth2/token
            jwk-set-uri: http://172.21.110.93:9000/oauth2/jwks
            user-info-uri: http://172.21.110.93:8000/user
            user-name-attribute: name